# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  trade-exports-packinglistai-ui:
    build:
      target: development
    image: trade-exports-packinglistai-ui-development
    container_name: trade-exports-packinglistai-ui-test
    command: npm run test
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.js:/home/node/jest.config.js
      - ./package.json:/home/node/package.json
