services:
  trade-exports-packinglistai-ui:
    build:
      context: .
      target: production
    image: trade-exports-packinglistai-ui
    container_name: trade-exports-packinglistai-ui
    environment:
      APPINSIGHTS_CLOUDROLE: trade-exports-packinglistai-ui-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      AI_API_VERSION: ${AI_API_VERSION}
      AI_AZURE_RESOURCE: ${AI_AZURE_RESOURCE}
      AI_OPENAI_KEY: ${AI_OPENAI_KEY}
      AI_OPENAI_MODEL: ${AI_OPENAI_MODEL}
      AI_PROMPT: ${AI_PROMPT}
