environment: development
environmentCode:
name: trade-exports-packinglistai-ui
namespace: trade-exports
workstream: trade-exports
image: trade-exports-packinglistai-ui

labels:
  component: web

appInsights:
  connectionString:

deployment: {}

container:
  memCpuTier: M
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: trade-exports-packinglistai-ui
  server: example.com