- key: NODE_ENV
  value: "production"
- key: PORT
  value: "3000"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"
- key: APPINSIGHTS_CONNECTIONSTRING
  value: "{{servicename}}-APPINSIGHTS-CONNECTIONSTRING" 
  type: "keyvault"    