{{- include "adp-helm-library.container-secret" (list . "trade-exports-packinglistai-ui.container-secret") -}}
{{- define "trade-exports-packinglistai-ui.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
